language: python
cache: pip
sudo: required
dist: xenial
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
# command to install dependencies
install:
  - python setup.py develop
  - pip install pytest coverage coveralls
script:
  - ./runtests.sh
after_success:
  - coveralls
notifications:
  email: false
  slack: friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
