sudo: false
language: python
cache: pip
os: linux
dist: trusty

matrix:
  include:
  - python: "2.7"
  - python: "3.3"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "pypy"
  - python: "pypy3"
  - python: "3.7"
    dist: xenial

# command to install dependencies
install:
  - python setup.py install
  - pip install pytest coverage coveralls
script:
  - ./runtests.sh
after_success:
  - coveralls
notifications:
  email: false
  slack: friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
