sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
# command to install dependencies
install:
  - python setup.py develop
  - pip install nose coverage
script: coverage run `which nosetests`
after_success:
  - coveralls
notifications:
  email: false
  slack: friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
